spring.application.name=siteLmix

#SQL
spring.datasource.url=jdbc:sqlite:lmix.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=4
spring.sql.init.mode=always
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
logging.level.org.hibernate.orm.connections.pooling=WARN
logging.level.org.hibernate.orm.core=WARN

#Thymeleaf
spring.thymeleaf.encoding=utf-8
spring.thymeleaf.mode=HTML
spring.thymeleaf.suffix=.html
spring.thymeleaf.prefix=classpath:/templates/
spring.mvc.static-path-pattern=/static/**

#App
lmix.dominio=https://lmix.top
lmix.subdominio=https://site.lmix.top

#Spring e Java
spring.threads.virtual.enabled=true

logging.level.org.springframework.web.servlet.PageNotFound=ERROR

